name: Build voyager Chef

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types:
      - trigger-voyager-automation-workflow
jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log event payload
      run: echo '${{ toJson(github.event.client_payload) }}'

    - name: Save event payload to file
      run: echo '${{ toJson(github.event.client_payload) }}' > file.json

    - name: Check if file.json exists and has content
      run: |
        if [ -s file.json ]; then
          echo "file.json exists and has content."
        else
          echo "file.json does not exist or is empty."
          exit 1
        fi
    - name: Print the location and contents of file.json
      run: |
        echo "Location of file.json: $(pwd)/file.json"
        echo "Contents of file.json:"
        cat file.json
        cat ${{ github.workspace }}/file.json
 
    - name: Extract projectName and write to file.json
      run: |
        projectName=$(jq -r '.client_payload.data' file.json)
        echo "Extracted projectName: $projectName"
        echo "$projectName" > file.json
    - name: Verify content of file.json
      run: |
        echo "Updated file.json content:"
        cat file.json
    - name: Read event payload into environment variable
      id: read_payload
      run: echo "EVENT_PAYLOAD=$(cat file.json | jq -c .)" >> $GITHUB_ENV
